export const FALLBACK_STATIONS = [
  { id: "1", station_id: "STW1066", station_name: "AWS Malang", table_name: "aws_malang", latitude: 0, longitude: 0, show_on_home: true, show_on_realtime: true, status: "Online" },
  { id: "2", station_id: "AWS-BATU", station_name: "AWS Batu", table_name: "aws_batu", latitude: 0, longitude: 0, show_on_home: true, show_on_realtime: true, status: "Online" },
  { id: "3", station_id: "AWS-BONDOWOSO", station_name: "AWS Bondowoso", table_name: "aws_bondowoso", latitude: 0, longitude: 0, show_on_home: true, show_on_realtime: true, status: "Online" },
  { id: "4", station_id: "AWS-BROMO", station_name: "AWS Bromo", table_name: "aws_bromo", latitude: 0, longitude: 0, show_on_home: true, show_on_realtime: true, status: "Online" },
  { id: "5", station_id: "AWS-KANDAT", station_name: "AWS Kandat", table_name: "aws_kandat", latitude: 0, longitude: 0, show_on_home: true, show_on_realtime: true, status: "Online" },
  { id: "6", station_id: "AWS-KANIGORO", station_name: "AWS Kanigoro", table_name: "aws_kanigoro", latitude: 0, longitude: 0, show_on_home: true, show_on_realtime: true, status: "Online" },
  { id: "7", station_id: "AWS-KARANGAN", station_name: "AWS Karangan", table_name: "aws_karangan", latitude: 0, longitude: 0, show_on_home: true, show_on_realtime: true, status: "Online" },
  { id: "8", station_id: "AWS-KEDIRI", station_name: "AWS Kediri", table_name: "aws_kediri", latitude: 0, longitude: 0, show_on_home: true, show_on_realtime: true, status: "Online" },
  { id: "9", station_id: "AWS-LAMONGAN", station_name: "AWS Lamongan", table_name: "aws_lamongan", latitude: 0, longitude: 0, show_on_home: true, show_on_realtime: true, status: "Online" },
  { id: "10", station_id: "AWS-MAYANG", station_name: "AWS Mayang", table_name: "aws_mayang", latitude: 0, longitude: 0, show_on_home: true, show_on_realtime: true, status: "Online" },
  { id: "11", station_id: "AWS-PANARUKAN", station_name: "AWS Panarukan", table_name: "aws_panarukan", latitude: 0, longitude: 0, show_on_home: true, show_on_realtime: true, status: "Online" },
  { id: "12", station_id: "AWS-PARON", station_name: "AWS Paron", table_name: "aws_paron", latitude: 0, longitude: 0, show_on_home: true, show_on_realtime: true, status: "Online" },
  { id: "13", station_id: "AWS-SAMPANG", station_name: "AWS Sampang", table_name: "aws_sampang", latitude: 0, longitude: 0, show_on_home: true, show_on_realtime: true, status: "Online" },
  { id: "14", station_id: "AWS-SITUBONDO", station_name: "AWS Situbondo", table_name: "aws_situbondo", latitude: 0, longitude: 0, show_on_home: true, show_on_realtime: true, status: "Online" },
  { id: "15", station_id: "AWS-SMPK-JOMBANG", station_name: "AWS SMPK Jombang", table_name: "aws_smpk_jombang", latitude: 0, longitude: 0, show_on_home: true, show_on_realtime: true, status: "Online" },
  { id: "16", station_id: "AWS-SMPK-MOJOKERTO", station_name: "AWS SMPK Mojokerto", table_name: "aws_smpk_mojokerto", latitude: 0, longitude: 0, show_on_home: true, show_on_realtime: true, status: "Online" },
  { id: "17", station_id: "AWS-SMPK-NGANJUK", station_name: "AWS SMPK Nganjuk", table_name: "aws_smpk_nganjuk", latitude: 0, longitude: 0, show_on_home: true, show_on_realtime: true, status: "Online" },
  { id: "18", station_id: "AWS-SMPK-SEBAYI", station_name: "AWS SMPK Sebayi", table_name: "aws_smpk_sebayi", latitude: 0, longitude: 0, show_on_home: true, show_on_realtime: true, status: "Online" },
  { id: "19", station_id: "AWS-STAGEOF-KARANGKATES", station_name: "AWS Stageof Karangkates", table_name: "aws_stageof_karangkates", latitude: 0, longitude: 0, show_on_home: true, show_on_realtime: true, status: "Online" },
  { id: "20", station_id: "AWS-STAGEOF-PASURUAN", station_name: "AWS Stageof Pasuruan", table_name: "aws_stageof_pasuruan", latitude: 0, longitude: 0, show_on_home: true, show_on_realtime: true, status: "Online" },
  { id: "21", station_id: "AWS-STAGEOF-SAWAHAN", station_name: "AWS Stageof Sawahan", table_name: "aws_stageof_sawahan", latitude: 0, longitude: 0, show_on_home: true, show_on_realtime: true, status: "Online" },
  { id: "22", station_id: "AWS-TIRIS", station_name: "AWS Tiris", table_name: "aws_tiris", latitude: 0, longitude: 0, show_on_home: true, show_on_realtime: true, status: "Online" },
  { id: "23", station_id: "AWS-UNIDA-GONTOR", station_name: "AWS Unida Gontor", table_name: "aws_unida_gontor", latitude: 0, longitude: 0, show_on_home: true, show_on_realtime: true, status: "Online" },
];
